spring:
  application:
    name: StudentRegistration
  datasource:
    url: jdbc:mysql://localhost:3306/student_registration?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    username: root
    password: password
    enabled: true
    baseline-version: 0

logging:
  file:
    name: ./log/studentRegistration.log
    max-history: 10
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
      refresh-token:
        expiration: 604800000